// Central data store for MahaKrushi AI

export const DISTRICTS = [
  { id: 1, name: "Nagpur", region: "Vidarbha", lat: 21.1458, lng: 79.0882 },
  { id: 2, name: "Amravati", region: "Vidarbha", lat: 20.9320, lng: 77.7523 },
  { id: 3, name: "Wardha", region: "Vidarbha", lat: 20.7453, lng: 78.6022 },
  { id: 4, name: "Yavatmal", region: "Vidarbha", lat: 20.3888, lng: 78.1204 },
  { id: 5, name: "Akola", region: "Vidarbha", lat: 20.7002, lng: 77.0082 },
  { id: 6, name: "Washim", region: "Vidarbha", lat: 20.1118, lng: 77.1339 },
  { id: 7, name: "Buldhana", region: "Vidarbha", lat: 20.5292, lng: 76.1842 },
  { id: 8, name: "Chandrapur", region: "Vidarbha", lat: 19.9615, lng: 79.2961 },
  { id: 9, name: "Gadchiroli", region: "Vidarbha", lat: 20.1809, lng: 80.0000 },
  { id: 10, name: "Gondia", region: "Vidarbha", lat: 21.4627, lng: 80.1961 },
  { id: 11, name: "Bhandara", region: "Vidarbha", lat: 21.1674, lng: 79.6519 },
  { id: 12, name: "Aurangabad", region: "Marathwada", lat: 19.8762, lng: 75.3433 },
  { id: 13, name: "Latur", region: "Marathwada", lat: 18.4088, lng: 76.5604 },
  { id: 14, name: "Osmanabad", region: "Marathwada", lat: 18.1861, lng: 76.0411 },
  { id: 15, name: "Beed", region: "Marathwada", lat: 18.9891, lng: 75.7601 },
  { id: 16, name: "Nanded", region: "Marathwada", lat: 19.1383, lng: 77.3210 },
  { id: 17, name: "Hingoli", region: "Marathwada", lat: 19.7177, lng: 77.1496 },
  { id: 18, name: "Parbhani", region: "Marathwada", lat: 19.2704, lng: 76.7742 },
  { id: 19, name: "Jalna", region: "Marathwada", lat: 19.8347, lng: 75.8816 },
  { id: 20, name: "Pune", region: "Western Maharashtra", lat: 18.5204, lng: 73.8567 },
  { id: 21, name: "Satara", region: "Western Maharashtra", lat: 17.6805, lng: 74.0183 },
  { id: 22, name: "Sangli", region: "Western Maharashtra", lat: 16.8524, lng: 74.5815 },
  { id: 23, name: "Kolhapur", region: "Western Maharashtra", lat: 16.7050, lng: 74.2433 },
  { id: 24, name: "Solapur", region: "Western Maharashtra", lat: 17.6599, lng: 75.9064 },
  { id: 25, name: "Ahmednagar", region: "Western Maharashtra", lat: 19.0952, lng: 74.7496 },
  { id: 26, name: "Raigad", region: "Konkan", lat: 18.5158, lng: 73.1179 },
  { id: 27, name: "Ratnagiri", region: "Konkan", lat: 16.9902, lng: 73.3120 },
  { id: 28, name: "Sindhudurg", region: "Konkan", lat: 16.3491, lng: 73.7145 },
  { id: 29, name: "Thane", region: "Konkan", lat: 19.2183, lng: 72.9781 },
  { id: 30, name: "Mumbai", region: "Konkan", lat: 19.0760, lng: 72.8777 },
  { id: 31, name: "Palghar", region: "Konkan", lat: 19.6967, lng: 72.7697 },
  { id: 32, name: "Nashik", region: "North Maharashtra", lat: 19.9975, lng: 73.7898 },
  { id: 33, name: "Dhule", region: "North Maharashtra", lat: 20.9042, lng: 74.7749 },
  { id: 34, name: "Jalgaon", region: "North Maharashtra", lat: 21.0077, lng: 75.5626 },
  { id: 35, name: "Nandurbar", region: "North Maharashtra", lat: 21.3666, lng: 74.2433 },
  { id: 36, name: "Akola", region: "North Maharashtra", lat: 20.7002, lng: 77.0082 },
];

export const WEATHER_DATA: Record<string, any> = {
  Nashik: { temp: 28, humidity: 65, rainfall: 5, wind: 12, condition: "Partly Cloudy", icon: "⛅", alerts: [], forecast: [{ day: "Today", high: 30, low: 20, rain: 10, icon: "⛅" }, { day: "Tue", high: 28, low: 19, rain: 40, icon: "🌧️" }, { day: "Wed", high: 25, low: 18, rain: 60, icon: "🌧️" }, { day: "Thu", high: 27, low: 19, rain: 20, icon: "⛅" }, { day: "Fri", high: 32, low: 22, rain: 5, icon: "☀️" }] },
  Pune: { temp: 32, humidity: 55, rainfall: 0, wind: 8, condition: "Sunny", icon: "☀️", alerts: [], forecast: [{ day: "Today", high: 34, low: 22, rain: 5, icon: "☀️" }, { day: "Tue", high: 33, low: 23, rain: 10, icon: "⛅" }, { day: "Wed", high: 30, low: 21, rain: 30, icon: "🌦️" }, { day: "Thu", high: 28, low: 20, rain: 50, icon: "🌧️" }, { day: "Fri", high: 29, low: 21, rain: 40, icon: "🌧️" }] },
  Nagpur: { temp: 38, humidity: 30, rainfall: 0, wind: 15, condition: "Hot & Dry", icon: "🔥", alerts: [{ type: "Heatwave", severity: "high", msg: "Heatwave alert! Temp above 40°C. Avoid fieldwork 11AM–4PM." }], forecast: [{ day: "Today", high: 40, low: 26, rain: 0, icon: "🔥" }, { day: "Tue", high: 41, low: 27, rain: 0, icon: "🔥" }, { day: "Wed", high: 39, low: 25, rain: 5, icon: "☀️" }, { day: "Thu", high: 37, low: 24, rain: 10, icon: "⛅" }, { day: "Fri", high: 36, low: 24, rain: 15, icon: "⛅" }] },
  Amravati: { temp: 36, humidity: 35, rainfall: 0, wind: 18, condition: "Very Hot", icon: "🔥", alerts: [{ type: "Heatwave", severity: "medium", msg: "High temp in Vidarbha. Irrigate cotton crops." }], forecast: [{ day: "Today", high: 38, low: 24, rain: 0, icon: "🔥" }, { day: "Tue", high: 37, low: 25, rain: 0, icon: "☀️" }, { day: "Wed", high: 35, low: 23, rain: 5, icon: "⛅" }, { day: "Thu", high: 33, low: 22, rain: 20, icon: "🌦️" }, { day: "Fri", high: 32, low: 21, rain: 25, icon: "🌦️" }] },
  Aurangabad: { temp: 33, humidity: 42, rainfall: 2, wind: 10, condition: "Clear", icon: "⛅", alerts: [], forecast: [{ day: "Today", high: 35, low: 22, rain: 5, icon: "⛅" }, { day: "Tue", high: 34, low: 23, rain: 15, icon: "🌦️" }, { day: "Wed", high: 31, low: 21, rain: 35, icon: "🌧️" }, { day: "Thu", high: 29, low: 20, rain: 45, icon: "🌧️" }, { day: "Fri", high: 30, low: 20, rain: 30, icon: "🌦️" }] },
  Kolhapur: { temp: 29, humidity: 72, rainfall: 12, wind: 20, condition: "Cloudy", icon: "🌧️", alerts: [{ type: "Heavy Rain", severity: "medium", msg: "Heavy rainfall for 3 days. Check drainage." }], forecast: [{ day: "Today", high: 30, low: 22, rain: 60, icon: "🌧️" }, { day: "Tue", high: 28, low: 21, rain: 70, icon: "🌧️" }, { day: "Wed", high: 27, low: 20, rain: 80, icon: "⛈️" }, { day: "Thu", high: 26, low: 19, rain: 90, icon: "⛈️" }, { day: "Fri", high: 25, low: 18, rain: 85, icon: "🌧️" }] },
  Latur: { temp: 34, humidity: 40, rainfall: 0, wind: 14, condition: "Dry", icon: "☀️", alerts: [{ type: "Drought Risk", severity: "high", msg: "Drought conditions in Marathwada. Conserve water." }], forecast: [{ day: "Today", high: 35, low: 23, rain: 0, icon: "☀️" }, { day: "Tue", high: 36, low: 24, rain: 5, icon: "☀️" }, { day: "Wed", high: 34, low: 22, rain: 10, icon: "⛅" }, { day: "Thu", high: 32, low: 21, rain: 20, icon: "🌦️" }, { day: "Fri", high: 31, low: 20, rain: 25, icon: "🌦️" }] },
  Solapur: { temp: 35, humidity: 38, rainfall: 0, wind: 16, condition: "Sunny", icon: "☀️", alerts: [], forecast: [{ day: "Today", high: 37, low: 24, rain: 0, icon: "☀️" }, { day: "Tue", high: 36, low: 25, rain: 5, icon: "⛅" }, { day: "Wed", high: 34, low: 23, rain: 10, icon: "⛅" }, { day: "Thu", high: 33, low: 22, rain: 20, icon: "🌦️" }, { day: "Fri", high: 32, low: 21, rain: 15, icon: "🌦️" }] },
};

export const CROP_HEALTH: Record<string, any> = {
  Nashik: { ndvi: 0.72, evi: 0.65, stress: "Low", growth: "Good", anomaly: false, recommendation: "Crop health optimal. Continue irrigation. Consider potassium for grape quality." },
  Pune: { ndvi: 0.68, evi: 0.61, stress: "Low", growth: "Good", anomaly: false, recommendation: "Good vegetation health. Sugar content in sugarcane appears high." },
  Nagpur: { ndvi: 0.45, evi: 0.38, stress: "High", growth: "Poor", anomaly: true, recommendation: "Vegetation stress due to heatwave. Immediate irrigation required. Cotton wilting detected." },
  Amravati: { ndvi: 0.48, evi: 0.41, stress: "High", growth: "Below Average", anomaly: true, recommendation: "High crop stress. Cotton bollworm risk elevated. Apply pesticides. Irrigate immediately." },
  Aurangabad: { ndvi: 0.60, evi: 0.54, stress: "Medium", growth: "Average", anomaly: false, recommendation: "Soybean requires additional nitrogen. Monitor for rust disease." },
  Kolhapur: { ndvi: 0.78, evi: 0.71, stress: "Very Low", growth: "Excellent", anomaly: false, recommendation: "Excellent crop health. Sugarcane thriving. Consider early harvesting for peak sugar content." },
  Latur: { ndvi: 0.42, evi: 0.35, stress: "Very High", growth: "Poor", anomaly: true, recommendation: "Critical drought stress. Soybean and tur severely impacted. Emergency irrigation needed." },
  Solapur: { ndvi: 0.55, evi: 0.48, stress: "Medium", growth: "Average", anomaly: false, recommendation: "Pomegranate health moderate. Monitor for bacterial blight. Apply boron foliar spray." },
};

export const MANDI_PRICES = [
  { mandi: "Lasalgaon", district: "Nashik", crop: "Onion", min: 800, max: 1200, modal: 1000, unit: "₹/quintal", trend: "up" },
  { mandi: "Pune Market Yard", district: "Pune", crop: "Tomato", min: 600, max: 1500, modal: 1000, unit: "₹/quintal", trend: "down" },
  { mandi: "Nagpur Mandi", district: "Nagpur", crop: "Orange", min: 1500, max: 3000, modal: 2200, unit: "₹/quintal", trend: "stable" },
  { mandi: "Solapur Mandi", district: "Solapur", crop: "Pomegranate", min: 4000, max: 8000, modal: 6000, unit: "₹/quintal", trend: "up" },
  { mandi: "Amravati Mandi", district: "Amravati", crop: "Cotton", min: 5500, max: 6500, modal: 6000, unit: "₹/quintal", trend: "stable" },
  { mandi: "Latur Mandi", district: "Latur", crop: "Soybean", min: 3800, max: 4500, modal: 4200, unit: "₹/quintal", trend: "up" },
  { mandi: "Nanded Mandi", district: "Nanded", crop: "Tur Dal", min: 6000, max: 7000, modal: 6500, unit: "₹/quintal", trend: "up" },
  { mandi: "Kolhapur Mandi", district: "Kolhapur", crop: "Sugarcane", min: 290, max: 310, modal: 300, unit: "₹/quintal", trend: "stable" },
  { mandi: "Jalgaon Mandi", district: "Jalgaon", crop: "Banana", min: 800, max: 1400, modal: 1100, unit: "₹/quintal", trend: "down" },
  { mandi: "Sangli Mandi", district: "Sangli", crop: "Grapes", min: 3000, max: 6000, modal: 4500, unit: "₹/quintal", trend: "up" },
  { mandi: "Wardha Mandi", district: "Wardha", crop: "Wheat", min: 2100, max: 2400, modal: 2250, unit: "₹/quintal", trend: "stable" },
  { mandi: "Ahmednagar Mandi", district: "Ahmednagar", crop: "Maize", min: 1500, max: 2000, modal: 1750, unit: "₹/quintal", trend: "up" },
];

export const LABS = [
  { id: 1, name: "Maharashtra State Soil Testing Lab", type: "Soil", cert: "ICAR", district: "Pune", city: "Pune", lat: 18.5314, lng: 73.8446, phone: "020-25537068", services: ["Soil nutrient analysis", "pH testing", "NPK analysis"], gov: "Government", hours: "Mon-Sat 9AM-5PM", address: "Agriculture College Campus, Shivajinagar, Pune" },
  { id: 2, name: "VNMKV Soil & Seed Lab", type: "Both", cert: "ICAR", district: "Parbhani", city: "Parbhani", lat: 19.2600, lng: 76.7800, phone: "02452-223801", services: ["Soil analysis", "Seed germination", "Seed purity"], gov: "Government", hours: "Mon-Fri 9AM-5PM", address: "VNMKV Campus, Parbhani" },
  { id: 3, name: "PDKV Agricultural Lab", type: "Both", cert: "ICAR", district: "Amravati", city: "Amravati", lat: 20.9320, lng: 77.7520, phone: "0721-2680258", services: ["Soil testing", "Seed testing", "Water analysis"], gov: "Government", hours: "Mon-Sat 9AM-5PM", address: "PDKV Campus, Amravati" },
  { id: 4, name: "MPKV Seed Testing Lab", type: "Seed", cert: "ICAR", district: "Ahmednagar", city: "Rahuri", lat: 19.3876, lng: 74.6504, phone: "02426-243214", services: ["Seed germination", "Seed purity", "Moisture content"], gov: "Government", hours: "Mon-Fri 9AM-5PM", address: "MPKV Campus, Rahuri" },
  { id: 5, name: "Nagpur District Soil Lab", type: "Soil", cert: "Maha Govt", district: "Nagpur", city: "Nagpur", lat: 21.1500, lng: 79.0900, phone: "0712-2562181", services: ["Soil nutrient analysis", "pH testing", "Organic matter"], gov: "Government", hours: "Mon-Sat 10AM-5PM", address: "Civil Lines, Nagpur" },
  { id: 6, name: "Nashik District Soil Lab", type: "Soil", cert: "Maha Govt", district: "Nashik", city: "Nashik", lat: 19.9975, lng: 73.7898, phone: "0253-2315451", services: ["Soil testing", "Grape soil analysis", "Onion soil testing"], gov: "Government", hours: "Mon-Fri 9AM-5PM", address: "Agri Office Complex, Nashik Road" },
  { id: 7, name: "Agritech Solutions Soil Lab", type: "Soil", cert: "ISO 9001", district: "Pune", city: "Pune", lat: 18.5018, lng: 73.8636, phone: "020-24440000", services: ["Complete soil analysis", "Carbon testing", "Enzyme activity"], gov: "Private", hours: "Mon-Sat 8AM-7PM", address: "Swargate, Pune" },
  { id: 8, name: "Konkan Krishi Lab", type: "Both", cert: "ICAR", district: "Ratnagiri", city: "Ratnagiri", lat: 16.9902, lng: 73.3120, phone: "02352-224532", services: ["Soil testing", "Coconut/Mango analysis", "Paddy seed testing"], gov: "Government", hours: "Mon-Sat 9AM-4:30PM", address: "Near MSRTC Depot, Ratnagiri" },
  { id: 9, name: "Aurangabad KVK Soil Lab", type: "Soil", cert: "ICAR", district: "Aurangabad", city: "Aurangabad", lat: 19.8790, lng: 75.3200, phone: "0240-2334455", services: ["Soil analysis", "Sugarcane soil", "Cotton soil"], gov: "Government", hours: "Mon-Sat 9AM-5PM", address: "KVK Campus, Aurangabad" },
  { id: 10, name: "Latur Seed Testing Lab", type: "Seed", cert: "Min of Agri", district: "Latur", city: "Latur", lat: 18.4088, lng: 76.5604, phone: "02382-248001", services: ["Seed purity", "Germination testing", "Vigour index"], gov: "Government", hours: "Mon-Fri 10AM-5PM", address: "Near Collectorate, Latur" },
  { id: 11, name: "Solapur Soil Testing Centre", type: "Soil", cert: "Maha Govt", district: "Solapur", city: "Solapur", lat: 17.6599, lng: 75.9064, phone: "0217-2302211", services: ["NPK testing", "pH testing", "Pomegranate analysis"], gov: "Government", hours: "Mon-Sat 9AM-5PM", address: "Agri Department, Solapur" },
  { id: 12, name: "Kolhapur Agri Testing Lab", type: "Both", cert: "ISO 9001", district: "Kolhapur", city: "Kolhapur", lat: 16.7050, lng: 74.2433, phone: "0231-2655441", services: ["Soil testing", "Sugarcane soil", "Water testing"], gov: "Private", hours: "Mon-Sat 8AM-6PM", address: "New Shahupuri, Kolhapur" },
  { id: 13, name: "Sangli Grape Research Lab", type: "Soil", cert: "NHB", district: "Sangli", city: "Sangli", lat: 16.8524, lng: 74.5815, phone: "0233-2323444", services: ["Grape soil analysis", "Micronutrient testing"], gov: "Government", hours: "Mon-Fri 9AM-4PM", address: "Grape Research Station, Sangli" },
  { id: 14, name: "Nanded Seed Testing Lab", type: "Seed", cert: "Min of Agri", district: "Nanded", city: "Nanded", lat: 19.1383, lng: 77.3210, phone: "02462-232100", services: ["Tur seed testing", "Soybean testing", "Cotton seed"], gov: "Government", hours: "Mon-Fri 10AM-5PM", address: "Agriculture Building, Nanded" },
  { id: 15, name: "Jalgaon Banana Crop Lab", type: "Soil", cert: "ICAR", district: "Jalgaon", city: "Jalgaon", lat: 21.0077, lng: 75.5626, phone: "0257-2228844", services: ["Banana crop soil", "Tissue testing", "Water analysis"], gov: "Government", hours: "Mon-Sat 9AM-5PM", address: "Banana Research Station, Jalgaon" },
];

export const EQUIPMENT = [
  { id: 1, name: "John Deere 5310 Tractor", category: "Tractor", brand: "John Deere", model: "5310", priceDay: 2500, priceHour: 400, district: "Nagpur", taluka: "Nagpur Rural", village: "Kamptee", lat: 21.2160, lng: 79.1955, phone: "9823000111", status: "Available", owner: "Rajesh Deshmukh" },
  { id: 2, name: "Mahindra 575 DI Tractor", category: "Tractor", brand: "Mahindra", model: "575 DI", priceDay: 2000, priceHour: 350, district: "Pune", taluka: "Haveli", village: "Loni Kalbhor", lat: 18.4924, lng: 73.9360, phone: "9822111222", status: "Available", owner: "Suresh Patil" },
  { id: 3, name: "Rotavator 7 Feet", category: "Rotavator", brand: "Fieldking", model: "FR-175", priceDay: 1200, priceHour: 200, district: "Nashik", taluka: "Niphad", village: "Lasalgaon", lat: 20.1180, lng: 74.2080, phone: "9823222333", status: "Available", owner: "Anand Kulkarni" },
  { id: 4, name: "Combine Harvester", category: "Harvester", brand: "CLAAS", model: "Crop Tiger 40", priceDay: 6000, priceHour: 800, district: "Amravati", taluka: "Daryapur", village: "Daryapur", lat: 20.9200, lng: 77.3300, phone: "9823333444", status: "Available", owner: "Vijay Wankhede" },
  { id: 5, name: "Drone Sprayer (10L)", category: "Drone Sprayer", brand: "DJI", model: "Agras T10", priceDay: 3500, priceHour: 600, district: "Aurangabad", taluka: "Gangapur", village: "Waluj", lat: 19.8400, lng: 75.3700, phone: "9823444555", status: "Available", owner: "Agrotech Solutions" },
  { id: 6, name: "Seed Drill 9 Tyne", category: "Seed Drill", brand: "Shaktiman", model: "SD-9", priceDay: 800, priceHour: 150, district: "Yavatmal", taluka: "Yavatmal", village: "Yavatmal", lat: 20.3888, lng: 78.1204, phone: "9823555666", status: "Available", owner: "Kisan Agri" },
  { id: 7, name: "Sugarcane Harvester", category: "Harvester", brand: "Austoft", model: "A7700", priceDay: 8000, priceHour: 1200, district: "Kolhapur", taluka: "Hatkanangle", village: "Shirol", lat: 16.7660, lng: 74.5700, phone: "9823666777", status: "Available", owner: "Sahyadri Agri Corp" },
  { id: 8, name: "Cultivator 9 Tyne", category: "Cultivator", brand: "Lemken", model: "Kristall 9", priceDay: 600, priceHour: 100, district: "Solapur", taluka: "Barshi", village: "Barshi", lat: 18.2344, lng: 75.6921, phone: "9823777888", status: "Available", owner: "Dattatray Mali" },
  { id: 9, name: "Boom Sprayer 500L", category: "Sprayer", brand: "ASPEE", model: "HTP-500", priceDay: 1500, priceHour: 250, district: "Sangli", taluka: "Walwa", village: "Islampur", lat: 17.0558, lng: 74.2653, phone: "9823888999", status: "Available", owner: "Warana Agri" },
  { id: 10, name: "Irrigation Pump (5HP)", category: "Pump", brand: "Kirloskar", model: "5HP Centrifugal", priceDay: 500, priceHour: 80, district: "Nashik", taluka: "Niphad", village: "Pimpalgaon Baswant", lat: 20.0815, lng: 74.0743, phone: "9823999000", status: "Available", owner: "Sanjay Jadhav" },
  { id: 11, name: "Thresher Machine", category: "Thresher", brand: "Kisan Craft", model: "Multi-Crop", priceDay: 1000, priceHour: 170, district: "Latur", taluka: "Udgir", village: "Udgir", lat: 18.3940, lng: 77.1000, phone: "9820111333", status: "Available", owner: "Pradeep Shinde" },
  { id: 12, name: "Cotton Picker", category: "Harvester", brand: "John Deere", model: "CP690", priceDay: 7000, priceHour: 1000, district: "Wardha", taluka: "Wardha", village: "Wardha", lat: 20.7453, lng: 78.6022, phone: "9820222444", status: "Booked", owner: "Wardha Agri Coop" },
  { id: 13, name: "Mini Tractor 25HP", category: "Tractor", brand: "Kubota", model: "B2441", priceDay: 1500, priceHour: 250, district: "Ratnagiri", taluka: "Ratnagiri", village: "Ratnagiri", lat: 16.9902, lng: 73.3120, phone: "9820333555", status: "Available", owner: "Konkan Agri Services" },
  { id: 14, name: "Laser Land Leveller", category: "Land Leveller", brand: "Trimble", model: "Pro", priceDay: 3000, priceHour: 500, district: "Jalgaon", taluka: "Jalgaon", village: "Jalgaon", lat: 21.0077, lng: 75.5626, phone: "9820444666", status: "Available", owner: "Smart Agri Jalgaon" },
  { id: 15, name: "Roto Tiller", category: "Rotavator", brand: "Sonalika", model: "RT-185", priceDay: 900, priceHour: 150, district: "Ahmednagar", taluka: "Rahata", village: "Shirdi", lat: 19.7659, lng: 74.4776, phone: "9820555777", status: "Available", owner: "Ganesh Agri Equipment" },
];

export const COLD_STORAGE = [
  { id: 1, name: "Maharashtra State Warehousing Cold Storage", type: "Cold Storage", district: "Nashik", city: "Nashik", lat: 20.0063, lng: 73.7900, phone: "0253-2314567", capacityTons: 5000, availableTons: 2000, tempRange: "2–8°C", crops: ["Grapes", "Onion", "Tomato", "Pomegranate"] },
  { id: 2, name: "Lasalgaon Onion Cold Storage", type: "Onion Storage", district: "Nashik", city: "Lasalgaon", lat: 20.1180, lng: 74.2080, phone: "02550-286222", capacityTons: 10000, availableTons: 4500, tempRange: "10–15°C", crops: ["Onion"] },
  { id: 3, name: "Mahagrapes Cold Chain Facility", type: "Fruit Storage", district: "Sangli", city: "Sangli", lat: 16.8650, lng: 74.5600, phone: "0233-2301010", capacityTons: 3000, availableTons: 1500, tempRange: "-1 to 4°C", crops: ["Grapes", "Pomegranate"] },
  { id: 4, name: "Pune Vegfresh Cold Storage", type: "Cold Storage", district: "Pune", city: "Pune", lat: 18.4922, lng: 73.8596, phone: "020-24261234", capacityTons: 8000, availableTons: 3000, tempRange: "0–10°C", crops: ["Tomato", "Potato", "Onion", "Vegetables"] },
  { id: 5, name: "Nagpur OrangeStore", type: "Fruit Storage", district: "Nagpur", city: "Nagpur", lat: 21.1800, lng: 79.1700, phone: "0712-2621111", capacityTons: 4000, availableTons: 1800, tempRange: "4–8°C", crops: ["Orange", "Pomegranate", "Banana"] },
  { id: 6, name: "Solapur APMC Cold Storage", type: "Cold Storage", district: "Solapur", city: "Solapur", lat: 17.6699, lng: 75.9200, phone: "0217-2302100", capacityTons: 6000, availableTons: 2500, tempRange: "5–15°C", crops: ["Pomegranate", "Onion", "Grapes"] },
  { id: 7, name: "Aurangabad AgriVault", type: "Grain Warehouse", district: "Aurangabad", city: "Aurangabad", lat: 19.8900, lng: 75.3900, phone: "0240-2481234", capacityTons: 15000, availableTons: 7000, tempRange: "Ambient", crops: ["Wheat", "Sorghum", "Maize", "Tur"] },
  { id: 8, name: "Kolhapur Sugarcane Storage", type: "Warehouse", district: "Kolhapur", city: "Kolhapur", lat: 16.6900, lng: 74.2200, phone: "0231-2662222", capacityTons: 20000, availableTons: 8000, tempRange: "Ambient", crops: ["Sugar", "Jaggery"] },
  { id: 9, name: "Amravati Cotton Warehouse", type: "Warehouse", district: "Amravati", city: "Amravati", lat: 20.9400, lng: 77.7700, phone: "0721-2562222", capacityTons: 25000, availableTons: 10000, tempRange: "Ambient", crops: ["Cotton", "Soybean"] },
  { id: 10, name: "Konkan Mango ColdChain", type: "Fruit Storage", district: "Ratnagiri", city: "Ratnagiri", lat: 16.9800, lng: 73.3000, phone: "02352-225555", capacityTons: 2000, availableTons: 900, tempRange: "8–13°C", crops: ["Mango", "Cashew", "Coconut"] },
  { id: 11, name: "Latur Soybean Storage", type: "Warehouse", district: "Latur", city: "Latur", lat: 18.4100, lng: 76.5700, phone: "02382-248100", capacityTons: 12000, availableTons: 5500, tempRange: "Ambient", crops: ["Soybean", "Tur", "Maize"] },
  { id: 12, name: "Jalgaon Banana Cold Storage", type: "Cold Storage", district: "Jalgaon", city: "Jalgaon", lat: 21.0000, lng: 75.5700, phone: "0257-2221111", capacityTons: 3500, availableTons: 1600, tempRange: "12–16°C", crops: ["Banana", "Papaya"] },
];

export const PEST_RISKS: Record<string, any> = {
  Nagpur: { pest: "Pink Bollworm", level: "Very High", score: 0.88, crop: "Cotton", color: "red", advice: "Install pheromone traps immediately. Spray Chlorpyrifos. Monitor daily." },
  Amravati: { pest: "Pink Bollworm", level: "High", score: 0.75, crop: "Cotton", color: "red", advice: "Preventive Bt sprays. Avoid late sowing." },
  Yavatmal: { pest: "Bollworm Complex", level: "High", score: 0.72, crop: "Cotton", color: "red", advice: "Light traps. Apply NPV @ 250 LE/ha." },
  Nashik: { pest: "Grape Berry Moth", level: "Medium", score: 0.55, crop: "Grapes", color: "amber", advice: "Spray Imidacloprid. Vineyard hygiene." },
  Latur: { pest: "Pod Borer", level: "Medium", score: 0.60, crop: "Tur", color: "amber", advice: "Light traps. Spray Quinalphos at flowering." },
  Pune: { pest: "Onion Thrips", level: "Low", score: 0.35, crop: "Onion", color: "green", advice: "Monitor regularly. Spray Fipronil if needed." },
  Aurangabad: { pest: "Stem Fly", level: "Medium", score: 0.58, crop: "Soybean", color: "amber", advice: "Seed treatment with Imidacloprid." },
  Kolhapur: { pest: "Sugarcane Pyrilla", level: "Low", score: 0.30, crop: "Sugarcane", color: "green", advice: "Release Epipyrops parasites." },
};

export const CROP_RECOMMENDATIONS: Record<string, any> = {
  Nashik: { primary: ["Grapes", "Onion", "Tomato"], secondary: ["Wheat", "Maize"], reason: "High rainfall, fertile soil. Close to Mumbai market." },
  Pune: { primary: ["Sugarcane", "Wheat", "Vegetables"], secondary: ["Onion", "Maize"], reason: "Good irrigation, diverse markets, favorable climate." },
  Nagpur: { primary: ["Orange", "Cotton", "Soybean"], secondary: ["Wheat", "Tur"], reason: "Famous Nagpur orange region. Vidarbha cotton belt." },
  Amravati: { primary: ["Cotton", "Soybean", "Tur"], secondary: ["Wheat", "Jowar"], reason: "Black cotton soil. Vidarbha's prime cotton zone." },
  Kolhapur: { primary: ["Sugarcane", "Rice", "Vegetables"], secondary: ["Banana", "Turmeric"], reason: "High rainfall, proximity to cooperatives." },
  Latur: { primary: ["Soybean", "Tur", "Cotton"], secondary: ["Jowar", "Wheat"], reason: "Marathwada dryland farming. Drought-resistant crops." },
  Solapur: { primary: ["Pomegranate", "Onion", "Jowar"], secondary: ["Cotton", "Groundnut"], reason: "Semi-arid conditions. Pomegranate thrives." },
  Aurangabad: { primary: ["Cotton", "Soybean", "Maize"], secondary: ["Tur", "Wheat"], reason: "Marathwada region. Mix of Kharif and Rabi." },
  Sangli: { primary: ["Grapes", "Sugarcane", "Turmeric"], secondary: ["Onion", "Chickpea"], reason: "Export-quality grapes. Major turmeric center." },
  Jalgaon: { primary: ["Banana", "Cotton", "Maize"], secondary: ["Wheat", "Tur"], reason: "Banana capital of India." },
};
